### PR TITLE
Throw QRCodeModal error asynchronously

### PR DESCRIPTION
**Pull request by nelsontky**
# Description

Closing the WalletConnect Modal causes the wallet connect button to be stuck in the "Connecting..." state. To reproduce the issue, go to http://poised-lumber.surge.sh/, click on any of the "Connect" buttons, and close the WalletConnect modal without connecting any wallet.

# How Has This Been Tested?

- [x] Connecting and disconnecting a wallet via https://react-wallet.walletconnect.com/
- [x] Rejecting a connection attempt
- [x] Closing the WalletConnect dialog without connecting to any wallet

### CODE REVIEW

**Comment by jnwng** [comment]
thank you for the PR! i am going to stage this after #2, so will need to make a couple of adjustments for consistency

**Comment by nelsontky** [comment]
> thank you for the PR! i am going to stage this after #2, so will need to make a couple of adjustments for consistency

Thank you for the update ser, I will be able to take a look after #2 is merged too!

**Comment by nelsontky** [comment]
> you should be able to pick up the latest changes at your soonest convenience! i think in this case you will only need one `new Promise` (and not the async iife) but could be sufficiently convinced otherwise

I have just rebased my branch to `main`! I used an iife to simplify the code - without the iife the `then` chaining gets a little messy and I feel that it is a little but more readable when using an iife.

**Comment by nelsontky** [comment]
@jnwng sorry for the tag any updates on this?

**Comment by jnwng** [comment]
> I used an iife to simplify the code

still don't quite understand why we need an IIFE here — the `new Promise((resolve, reject) => { ... })` seems like all that is needed. what does the IIFE achieve here? my understanding is that the callback will get executed anyway

**Comment by nelsontky** [comment]
> > I used an iife to simplify the code
> 
> still don't quite understand why we need an IIFE here — the `new Promise((resolve, reject) => { ... })` seems like all that is needed. what does the IIFE achieve here? my understanding is that the callback will get executed anyway

@jnwng I have refactored the code to not use an iffe!

I used an iffe initially as I wanted to use `await` within the `Promise` executor so that I can avoid the use of `.then`. (The `connect` method depends on numerous calls to async functions) I did not use an async function as the `Promise` executor as eslint complains about it 😂 (https://eslint.org/docs/latest/rules/no-async-promise-executor)

**Comment by nelsontky** [comment]
Sorry for the tag @jnwng bumping this again!

**Pull request merged**
